name: como_gasto
description: "An app to help track your expenses."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  get_it: ^7.0.0
  firebase_auth: ^4.7.0
  shared_preferences: ^2.1.0
  flutter_hooks: ^0.20.5
  firebase_storage: ^11.0.1
  uuid: ^4.4.2
  rect_getter: ^1.0.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.1+2
  flutter_charts: ^0.5.2
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  google_sign_in: ^6.0.0 # Añadido para importar GoogleSignIn

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  test: ^1.22.0

flutter:
  uses-material-design: true
